[gcp_service_account]
type = "service_account"
project_id = "elite-totality-470308-a3"
private_key_id = "010b17c4564955ccd72273fe6b466bbc710a4e9d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYm67HC9W4FCSn
LXGU/opfHx5P2kY9H/idhddJYE9cHGANf55uGanSr2jcJe+zy3OyTb5smOECrNjZ
bnHsBD2iDhrd4LdsQWHcKVrAHUhi4xRFCj3+iFMRzrGjs4dJn8RpQRgzta5g70DH
sWSlxZnRQ3mDNprurjwCUpksHrJ0TFqFtcUhh4ODQkKIhbOOs40keduSavd6w2sN
339Yk3rVnotkSFwFUjFR7GzUY8Dez5iAvWaGTPkNY0LU4OWQOzyKsJtr3asBXph+
k95Y3Zd2/SnE/Wrfpe00u8qK95Jj24UD4BnLDO3IckX/pgxlKQUJ3M+PuEc+hi0p
usbZipUdAgMBAAECggEAQd6Z+EKzk75gZQxPOYFsX7/NTngwmt7xkimEzfYBPCAO
35v6+D1KpNydtTC+I31Pqh21Nj4JUvBwIzLQZvblLTY/2lA/Rybc1QAobjqZbCTk
4ZfbQV+Ab25dG8x47B0vM9jNPNBXfnfTSca6tiSQgZAU0B+XXtTSP9yRYtbU6sNL
47EX8HQeq42ZKmapb/G1kPdzMhA24Gp4I9j0ThtvC07crB5sc2lzJ1gsgDMwgOhv
ljiMSw0WNksuEnBbyBsPs9vBTErTE0r3nbTFUGfuaGjJXuyUh0gUMuu5PX5oLt8b
ByF0VWQ10yAxdlctcgd/3OAGv873ca375hRUrqtf6wKBgQD5FM2iDQno8lJgR/bW
PxUOp1qADbT0BeudkQUhG0F8sQQLVAQRjA49zMwE3W8fq3uEPFpC0dHkkbAmFyKm
5PrRtjjiA92/MMRw2qgGTt9Pf9JHTBwSa5K8M6PuMWMiSG+byKx+wdM/LetGKCYV
witwE/Nm6G/kwEY44pH3eE5zWwKBgQDen/c3OIii4z8Dq0+cKIxeiKuRbGcHVYJH
MVJQvQTAi/h+7vOIIHEM2N3/fTzZg1EXu7zJV/bVoFk/mGcebYGin9xBfRB6/KD6
E20Zaa5Y6rlwHuzmhH8MDGRBh4aH13QU+q+3l9Od+j5j6z9n4moyT3oVZh2qHdcq
90cxNZ/a5wKBgBTiaKd4vmb4wm1uO0UVfvd+krj/7Tc0s9+/RBXVijUhRnyIq9qo
ypzl6glSY7ndD/szcEIAA8BNct6OvAoQUvN4euaAenxIY4Au5T26KUEqL4Bo4kWt
HV2IWuti2rQKLMl8FvJ93++BMyPrw925LRk1owfy30bn1Dt6y9BbFwDXAoGAbiAN
Z4iUtpbZHhSJLgM05LKQxEAuewdGibcRNBU8m47h3tCPMYByy9sfffnStvppi+b3
jVXxKV3HqFjYccnTvcF8b/zQwTXk36/qYQ7RCvUZxCfYInPacPhUQ8Ipv1rJ9nLH
p3b4XIZkhILje50Z0UdVae54sCVQwdVOpz4SlHMCgYEA9EabNHgTb49Ob6XeJYp7
jYDuI3TdHtsRHLKR0DKA+YQaLPt6Z2cqvG2uiuC1ZB4hXHPuuF2MEO/WCExxAxnY
sbOM2pxV64MhK7UPrO5zy9dVSlQjYCiHlWMmRM/Nv4GlQ7hFJNgixaC0bV1wNveE
FKMI4NyHloZ4jqIvSpXLrm4=
-----END PRIVATE KEY-----
"""
client_email = "stramlit-app@elite-totality-470308-a3.iam.gserviceaccount.com"
client_id = "109357013461675900437"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/stramlit-app%40elite-totality-470308-a3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
